sudo: false

language: python

matrix:
  include:
    # OSX doesn't work with `language: python` yet
    - os: osx
      language: generic
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy

addons:
  apt:
    packages:
      - libenchant-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 enchant; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv ./venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source ./venv/bin/activate; fi

script:
  - python setup.py test

notifications:
  - email: ryan@rfk.id.au
